/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'post-categories': PostCategory;
    posts: Post;
    'open-source': OpenSource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'open-source': OpenSourceSelect<false> | OpenSourceSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    cv: Cv;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    cv: CvSelect<false> | CvSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Products, companies, websites, concepts, brands, and independent initiatives. Not a client portfolio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description: string;
  /**
   * Optional eyebrow shown on the project detail page.
   */
  eyebrow?: string | null;
  status: 'active' | 'in-progress' | 'concept' | 'paused' | 'archived' | 'future';
  /**
   * Controls whether this project is visible on the public site.
   */
  published?: boolean | null;
  type: 'company' | 'product' | 'website' | 'brand' | 'concept' | 'experiment';
  /**
   * Short role label, e.g. Founder, Technical partner, Architect.
   */
  role?: string | null;
  /**
   * Optional focus line shown in the project detail metadata.
   */
  focus?: string | null;
  startedAt?: string | null;
  year?: number | null;
  previewImage?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  externalUrl?: string | null;
  featured?: boolean | null;
  order?: number | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Temporary post slug references. Convert to relationship after Posts collection is added.
   */
  relatedPosts?:
    | {
        slug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional, manually selected posts for the Selected case notes section.
   */
  selectedCaseNotes?: (number | Post)[] | null;
  /**
   * Optional, manually selected posts for the Related writing section.
   */
  relatedWriting?: (number | Post)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Articles, notes, case notes, guides, and essays.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description: string;
  /**
   * Optional eyebrow shown on the post detail page.
   */
  eyebrow?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  /**
   * Estimated reading time in minutes.
   */
  readingTime?: number | null;
  category?: ('article' | 'case' | 'note' | 'guide' | 'essay') | null;
  postCategory: number | PostCategory;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  previewImage?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  featured?: boolean | null;
  showOnHome?: boolean | null;
  relatedProjects?: (number | Project)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Configurable post categories used across the public posts pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Used in post meta and detail header, for example "Case note".
   */
  singularLabel: string;
  /**
   * Optional introduction for the category page.
   */
  description?: string | null;
  /**
   * Optional eyebrow shown on the category page.
   */
  eyebrow?: string | null;
  order?: number | null;
  /**
   * Controls whether this category appears in the /posts navigation.
   */
  showInPostsNavigation?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Open-source work used as a credibility block on the home page, not a standalone public section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-source".
 */
export interface OpenSource {
  id: number;
  name: string;
  description: string;
  /**
   * GitHub repository URL.
   */
  githubUrl: string;
  /**
   * Optional external article URL or internal /posts/:slug path.
   */
  articleUrl?: string | null;
  stars?: number | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'open-source';
        value: number | OpenSource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  eyebrow?: T;
  status?: T;
  published?: T;
  type?: T;
  role?: T;
  focus?: T;
  startedAt?: T;
  year?: T;
  previewImage?: T;
  coverImage?: T;
  externalUrl?: T;
  featured?: T;
  order?: T;
  content?: T;
  relatedPosts?:
    | T
    | {
        slug?: T;
        id?: T;
      };
  selectedCaseNotes?: T;
  relatedWriting?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  singularLabel?: T;
  description?: T;
  eyebrow?: T;
  order?: T;
  showInPostsNavigation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  eyebrow?: T;
  content?: T;
  publishedAt?: T;
  readingTime?: T;
  category?: T;
  postCategory?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  previewImage?: T;
  coverImage?: T;
  featured?: T;
  showOnHome?: T;
  relatedProjects?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open-source_select".
 */
export interface OpenSourceSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  githubUrl?: T;
  articleUrl?: T;
  stars?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  telegram?: string | null;
  linkedin?: string | null;
  github?: string | null;
  location?: string | null;
  availability?: string | null;
  /**
   * Optional eyebrow shown on the home page hero.
   */
  homeEyebrow?: string | null;
  /**
   * Optional eyebrow shown on the projects index page.
   */
  projectsEyebrow?: string | null;
  /**
   * Optional eyebrow shown on the posts index page.
   */
  postsEyebrow?: string | null;
  bookingUrl?: string | null;
  /**
   * Posts selected and ordered manually for the home page. Caption is a free-text label, not a post category.
   */
  selectedWork?:
    | {
        post: number | Post;
        /**
         * Short label shown to the right of the post, for example “Architecture”.
         */
        caption: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Services shown on the home page. These do not have a separate collection or route.
   */
  services?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    defaultTitle: string;
    defaultDescription: string;
    defaultImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Formal professional profile data for the /cv page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv".
 */
export interface Cv {
  id: number;
  /**
   * Name displayed on the formal CV page.
   */
  name?: string | null;
  /**
   * Optional eyebrow shown above the CV title.
   */
  eyebrow?: string | null;
  /**
   * Current professional title or positioning.
   */
  role?: string | null;
  /**
   * Optional current location shown in the profile summary.
   */
  location?: string | null;
  /**
   * Short formal profile summary.
   */
  summary?: string | null;
  /**
   * Optional short focus line for the profile summary block.
   */
  focus?: string | null;
  /**
   * Optional primary stack line for the profile summary block.
   */
  stack?: string | null;
  /**
   * Optional short note shown next to the key expertise section title.
   */
  expertiseNote?: string | null;
  /**
   * Optional expertise cards shown before experience.
   */
  expertise?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional professional experience entries.
   */
  experience?:
    | {
        company?: string | null;
        role?: string | null;
        location?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        current?: boolean | null;
        summary?: string | null;
        stack?: string | null;
        highlights?:
          | {
              text?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional skill groups for the formal CV.
   */
  skills?:
    | {
        category?: string | null;
        items?:
          | {
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional education entries.
   */
  education?:
    | {
        institution?: string | null;
        degree?: string | null;
        field?: string | null;
        startYear?: number | null;
        endYear?: number | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional language proficiency entries.
   */
  languages?:
    | {
        language?: string | null;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional PDF version of the CV.
   */
  pdf?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  telegram?: T;
  linkedin?: T;
  github?: T;
  location?: T;
  availability?: T;
  homeEyebrow?: T;
  projectsEyebrow?: T;
  postsEyebrow?: T;
  bookingUrl?: T;
  selectedWork?:
    | T
    | {
        post?: T;
        caption?: T;
        id?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        defaultImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cv_select".
 */
export interface CvSelect<T extends boolean = true> {
  name?: T;
  eyebrow?: T;
  role?: T;
  location?: T;
  summary?: T;
  focus?: T;
  stack?: T;
  expertiseNote?: T;
  expertise?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        company?: T;
        role?: T;
        location?: T;
        startDate?: T;
        endDate?: T;
        current?: T;
        summary?: T;
        stack?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  skills?:
    | T
    | {
        category?: T;
        items?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  education?:
    | T
    | {
        institution?: T;
        degree?: T;
        field?: T;
        startYear?: T;
        endYear?: T;
        description?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  pdf?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}